# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
    exception:
        exception_controller: fos_rest.exception.controller::showAction
        codes:
            Symfony\Component\Routing\Exception\ResourceNotFoundException: 404